### ISSUE TITLE
Error when building in Xcode 10.2

### ISSUE THREAD

**Issue by LiborZa** [cometchat-pro/ios-chat-sdk#1]
Hi,
I get this error when running my app in Xcode 10.2: `Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0 compiler`. Could you fix it? 
Thanks

**Comment by ghanshyammansata** [comment]
@LiborZa, we haven't started supporting the latest Swift 5 yet. We will surely update our SDK to support the latest Swift 5 soon.

**Comment by LiborZa** [comment]
@ghanshyammansata Any info about when it could be?

**Comment by ghanshyammansata** [comment]
Hey @LiborZa, I have released a new version which is compatible with Xcode 10.2 and Swift 5. Sorry for the delay. I am closing this issue. If you have any issue further you can continue to comment or you can reopen the issue.
