### ISSUE TITLE
Use of undeclared identifier 'CometChat' issue

### ISSUE THREAD

**Issue by SergeyBazhanov** [cometchat-pro/ios-chat-sdk#10]
Hello, guys. Thank for this awesome library. I'm trying to integrate this sdk into my react-native application in order to make wrapper for it and use as regular native module.

I use manual integration steps. I added CometChatPro.framework, JitsiMeet.framework and WebRTC.framework into my project. Added them to Embedded Binaries. Set "Enable Bitcode" to No. Set "Always Embed Swift Standard Libraries" to Yes. Added "$(SDKROOT)/usr/include/libxml2" to my "Header Search Paths". 
Application is built successfully until i'm trying to init CometChat as mentioned in the docs.
I make "#import <CometChatPro/CometChatPro-Swift.h>" in my AppDelegate.m. And when i try to call
```
[[CometChat alloc]initWithAppId:@"4152a64155ab75" onSuccess:^(BOOL isSuccess) {
    
    if (isSuccess) {
      NSLog(@"Successfully init CometChatPro");
    }
    
  } onError:^(CometChatException * error) {
    
    NSLog(@"Error in init %@",[error errorDescription]);
    
  }];
```
XCode gives me compilation error: "Use of undeclared identifier 'CometChat'"

I see "@interface CometChat : NSObject" inside "CometChatPro.framework/Headers/CometChatPro-Swift.h" file
But it seems XCode can't see it.

Could you please point me what i'm doing wrong?

ios-chat-sdk version 1.6.1
Also tried removing DerivedData and Clean project

Thank you

**Comment by TopXTeam** [comment]
Update: The same issue if use cocoapods. Issue is reproduced in Objective-c project. Integration in Swift project works well

**Comment by SergeyBazhanov** [comment]
Update: The same issue if use cocoapods approach. Issue is reproduced only in Objective-c project. Integration in Swift project works well

**Comment by SergeyBazhanov** [comment]
Do you prefix CometChat class with @objc annotation?

**Comment by pushpsenairekar2911** [comment]
Hello @SergeyBazhanov, 

We have already created our sample app with Objective C which uses the latest framework i.e. v1.6.1. Here is the link: https://github.com/cometchat-pro-samples/ios-objective-c-chat-app. Kindly, check. 
![Screenshot 2019-06-10 at 4 02 20 PM](https://user-images.githubusercontent.com/40260295/59190323-0c5a9c00-8b9a-11e9-902a-609b769ceac7.png)
Also, please check '-ObjC' and '$(inherited)' flag is added in  'Build Settings' --> 'Other Linker Flags'. ..

**Comment by vymallesh** [comment]
I had done the same, not working in Objective C, works well in Swift.
@ghanshyammansata , downloaded sample project as well, ends up with same issue in your project too.Kindly , let me know the issue..

**Comment by jeetkapadia** [comment]
Hi,

Please refer the Objective-C sample app from the below link:-

https://github.com/cometchat-pro-samples/ios-objective-c-chat-app

Steps to integrate the app.
Using “Pod install” install the CometChat Pro SDK in your app.
Drag and Drop or Copy the following Folders in the app.
1. CometChatProRequests Folder in your app (This file contains all the method that have been exposed for use by the SDK and are made global so that it can be used in the entire files of objective-c app.)
2. “AppConstant.h” file in your app.( keep <CometChatPro/CometChatPro-Swift.h> line and delete the other and add the .h file of the ViewController in which the CometChat Pro SDK Methods will be used.
3. import “Appconstants.h” in viewcontroller.h i.e (where CometChat SDK methods will be used)
Please let us know if you still face any issues.

**Comment by vymallesh** [comment]
Yeah, now it started working, previously i was importing <CometChatPro/CometChatPro-Swift.h>, now i imported in AppConstants file.What was the issue..

**Comment by jeetkapadia** [comment]
Since our SDK is in Swift language we need to create a bridge for linking the methods from swift to objective c.  So we bridged the methods and asked you to perform the above steps so that your apps also contain the same.

**Comment by vymallesh** [comment]
OK, Cool !! Thank you for your contribution @jeetkapadia

**Comment by vymallesh** [comment]
Hello @jeetkapadia 

I can be able to send the message, but i didn't be able to get the call back for Read Receipts, Delivered messages, Received Messages. 

1.In my viewcontroller.m , i had imported the delegate method.. <CometChatMessageDelegate>
2.CometChat.messagedelegate = self ;

3.None of the below methods getting called
- (void)onMessagesReadWithReceipt:(MessageReceipt * _Nonnull)receipt{
    NSLog(@"Message Read");
    
}

- (void)onMessagesDeliveredWithReceipt:(MessageReceipt * _Nonnull)receipt{
    NSLog(@"Message Delivered");
    
}


-(void)onTextMessageReceivedWithTextMessage:(TextMessage *)textMessage{
    
    if ([textMessage isKindOfClass:TextMessage.class]) {
        
        TextMessage *messageReceived = (TextMessage *)textMessage;
        NSLog(@"TextMessage received successfully. %@",[messageReceived stringValue]);
    }
    
}


Please let me know the issue..

**Comment by NishantTiwarins** [comment]
Hi 

have you added  [self delegate].messagedelegate = self; in viewDidLoad method. Please check and let us know if you still face issue

**Comment by vymallesh** [comment]
Hello !!

Messages were sent and received successfully, i had made few conversations.Trying to fetch those using below method.It was not entering into neither success nor failure block.Not able to find the issue..

-(void)fetchPreviousMessages{
    
    NSInteger limit = 5;
    NSString *uid = _receiverID;

    MessagesRequest *messageRequest = [[[[[MessageRequestBuilder alloc]init]setWithUid:uid]setWithLimit:limit]build];

    [messageRequest fetchPreviousOnSuccess:^(NSArray<BaseMessage *> * messages) {

      for (BaseMessage *message in messages) {

          if ([message isKindOfClass:TextMessage.self]) {

              TextMessage *receivedMessage = (TextMessage *)message;
              NSLog(@"TextMessage received successfully. %@",[receivedMessage stringValue]);
          }
          else if ([messages isKindOfClass:MediaMessage.self]) {

              MediaMessage *receivedMessage = (MediaMessage *)message;
              NSLog(@"MediaMessage received successfully. %@",[receivedMessage stringValue]);
          }
      }

    } onError:^(CometChatException * error) {

        NSLog(@"Message receiving failed with error: %@",[error errorDescription]);

    }];


}

**Comment by vymallesh** [comment]
> Hi
> 
> have you added [self delegate].messagedelegate = self; in viewDidLoad method. Please check and let us know if you still face issue

Yeah, i have declared it - CometChat.messagedelegate = self ; like this.It worked !!

Thank you !!
