### ISSUE TITLE
TMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSCalendarsUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data"

### ISSUE THREAD

**Issue by pushpsenairekar2911** [cometchat-pro/ios-chat-sdk#17]
TMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain an NSCalendarsUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data"

**Comment by jeetkapadia** [comment]
The issue has been fixed

**Comment by DeepakSoni87** [comment]
@jeetkapadia What you have fixed.

**Comment by voyager163** [comment]
Hi Jeetkapadia,

The app is still asking for this permission. Can i know how u fix it?

**Comment by NishantTiwarins** [comment]
Hi @voyager163 @DeepakSoni87 

We have removed this permission long back and have still tried today to validate the app and its has been validated successfully. You can try with version 2.0.8

**Comment by keremkusmezer** [comment]
Any progress on this, i just got a rejection email therefore.
We identified one or more issues with a recent delivery for your app, “Remtime” 1.158 (133). Please correct the following issues, then upload again.
ITMS-90683: Missing Purpose String in Info.plist - Your app’s code references one or more APIs that access sensitive user data. The app’s Info.plist file should contain a NSCalendarsUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you’re using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn’t contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).
Best regards,
The App Store Team
