### ISSUE TITLE
[1.8.4] User Online/Offline events not working sometimes

### ISSUE THREAD

**Issue by pushpsenairekar2911** [cometchat-pro/ios-chat-sdk#20]
**Describe the bug**
After login,  User Online/Offline events not working sometimes.

**To Reproduce**
1. Login with superhero1 and superhero2
2. check the status

**Expected behavior**
one of the user not able to see the online status of another

**Actual behavior**
one of the user not able to see the online status of another

**Screenshots** (optional)

**Enviorment/Platfrom (please complete the following information):**
 - iOS Version[ e.g iOS 12.1 ]
 - CometChat SDK Version[1.8.4]

**Files (Optional)**
 - `podfile` 

**Logs (Error Logs)**
- Error Log
- Debug Log

**Additional context**

**Comment by jeetkapadia** [comment]
The issue fixed in version 1.8.6
