### ISSUE TITLE
[1.8.5]  EXC_BAD_ACCESS (code=1, address=0x60) when adding 1000 limit in BlockedUserRequestBuilder, MessageRequestBuilder

### ISSUE THREAD

**Issue by pushpsenairekar2911** [cometchat-pro/ios-chat-sdk#23]
**Describe the bug**
When we add limit 1000 in BlockedUserRequestBuilder, MessageRequestBuilder the below error is thrown: EXC_BAD_ACCESS (code=1, address=0x60)

**To Reproduce**
1. BlockedUserRequest.BlockedUserRequestBuilder(limit: 1000).build()
1.MessagesRequest.MessageRequestBuilder().set(uid: TestConstants.user2).set(limit: 1000).build()

**Expected behavior**
SDK should not crash as like userRequest  class.

**Actual behavior**
SDK is crashing

**Screenshots** (optional)
--

**Enviorment/Platfrom (please complete the following information):**
 - CometChat SDK Version[  1.8.5]

**Comment by jeetkapadia** [comment]
This issue is fixed. Please use the latest version v1.8.12 for v1 and v2.0.4 for v2.
