### ISSUE TITLE
[1.8.5] MessageRequestBuilder not fetching messages are per specified limit

### ISSUE THREAD

**Issue by pushpsenairekar2911** [cometchat-pro/ios-chat-sdk#25]
**Describe the bug**
When we fetch the messages with a limit of 30 in a group. It is fetching 100 messages at a time. 

**To Reproduce**
1. Create an object of messageRequest  class and set limit 30
2. pull the messages

**Expected behavior**
It has to pull only 30 messages at a time. 

**Actual behavior**
Pulling 100 messages

**Enviorment/Platfrom (please complete the following information):**
 - iOS Version[ e.g iOS 12.1 ]
 - CometChat SDK Version[ e.g. 1.8.5]

**Files (Optional)**
 - `podfile` 

**Logs (Error Logs)**
- Error Log
- Debug Log

**Additional context**

**Comment by jeetkapadia** [comment]
The issue fixed in version 1.8.6
