### ISSUE TITLE
[Sample of objective-c] Use of undeclared identifier 'CometChat' issue

### ISSUE THREAD

**Issue by tiny9085** [cometchat-pro/ios-chat-sdk#28]
AppDelegate 
-(BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
[[CometChat alloc]initWithAppId:@APP_ID onSuccess:^(BOOL isSuccess) {
        
        // Successfully init CometChat
        NSLog(isSuccess ? @"YES" : @"NO");
        
        CometChat.messagedelegate = self;
        CometChat.userdelegate    = self;
        CometChat.groupdelegate   = self;
        CometChat.calldelegate    = self;
        [[CallManager sharedInstance] setDelegate:self];
        
        [self switchViewControllerIfLoggedIn];
        
        
    } onError:^(CometChatException * error) {
        // Error in init CometChat
        NSLog(@"Error %@",[error errorDescription]);
    }];
return YES;
}
Use of undeclared identifier 'CometChat' issue

**Comment by pushpsenairekar2911** [comment]
Hello @tiny9085, 

It seems that pods are not installed properly. Kindly,  use 'pod install' command to install the pods.
Also, please check '-ObjC' and '$(inherited)' flag is added in  'Build Settings' --> 'Other Linker Flags'. ..
![Screenshot 2019-06-10 at 4 02 20 PM](https://user-images.githubusercontent.com/40260295/59190323-0c5a9c00-8b9a-11e9-902a-609b769ceac7.png)

**Comment by tiny9085** [comment]
I followed your steps,but this problem also exist,Xcode version 10.3,CometChatPro version 1.8.3

**Comment by tiny9085** [comment]
Swift project works well,but objective-c cannot run

**Comment by tiny9085** [comment]
Xcode 10.2.1 also build failed!  i use 'pod install'

**Comment by pushpsenairekar2911** [comment]
@tiny9085  We have tested it at our end and it is working properly. Closing this issue because no action needed.  If you're still facing this issue with our latest SDK versions then you can reopen this issue.
