### ISSUE TITLE
Notifications banners not showing when app is in background

### ISSUE THREAD

**Issue by LiborZa** [cometchat-pro/ios-chat-sdk#3]
Hi,
I have implemented Firebase and enable it in CometChat and when I am in app and using `CometChatMessageDelegate` I get new messages. But when app is in background or is killed I want to receive "classic" system notifications (on lock screen etc.). How can I enable this?
Thanks for info 

Bonus question: Is there any property or any method that tells me this user/group has new unread messages and maybe how many?

**Comment by pushpsenairekar2911** [comment]
Hello LiborZa, 

Hope your day is going well. 

You need to perform some steps to implement push notifications inside your iOS Project. You can refer the below link to implement the same. 

https://prodocs.cometchat.com/v1.3/docs/extensions-ios-push-notifications

Do not hesitate to contact us if you have any queries/concerns. We'll be glad to assist you.

Warm Regards,
Pushpsen A.
CometChatPro Team

**Comment by LiborZa** [comment]
Hi Pushpsen,

I have implemented Push Notifications and it's working when I am in application (app is in running state). My problem is that I don't get system notification banner when I am outside of the app. I am including image to explain what I am missing and what I want to:

![image](https://user-images.githubusercontent.com/39513305/56018956-c309df80-5d03-11e9-9483-ca0c04771967.png)

And still:
Bonus question: Is there any property or any method that tells me this user/group has new unread messages and maybe how many?

Thanks for help

**Comment by bhooshanpatil** [comment]
Hello @LiborZa,
May I know the steps that you have followed for implementing Firebase in your iOS app? (e.g code snippet of your sample code )
**An answer to your bonus question:**
you can always get a particular user/group 's unread messages by using `MessagesRequest`  class as follows:
```
let messagesRequest = MessagesRequest.MessageRequestBuilder().set(UID: buddyUID).set(messageID: "last_read_message_id_of_paticular_user_you_have_in_your_app").build()

messagesRequest.fetchNext(onSuccess: { (messages) in

  if let receivedMessages = messages {

    // get message count //

    for message in receivedMessages {

      // get message //
    }
  }

}) { (error) in

  print(error ? .errorDescription as Any);
}
```

**Comment by LiborZa** [comment]
Hello @bhooshanpatil,

I added same code snippets as in article: https://prodocs.cometchat.com/docs/extensions-ios-push-notifications Same codes in AppDelegate and after CometChat.login method I call subscribe to topic:

```
let userTopic: String = Constants.cometChat.appId + "_user_" + uid + "_ios"
Messaging.messaging().subscribe(toTopic: userTopic) { error in
      print("Subscribed to \(userTopic) topic")
}
```

In my chat controller I set delegate and get new messages with this:

```
extension MessagesViewController: CometChatMessageDelegate {
    
    func onTextMessageReceived(textMessage: TextMessage?, error: CometChatException?) {
      ....
    }
```

So I am receiving new messages by that CometChatMessageDelegate method. That's okay and working. When I send test push notification from Firebase console I am getting banner when I am in lock screen:
![IMG_7994](https://user-images.githubusercontent.com/39513305/56156253-24100c80-5fbd-11e9-83fc-864bcbd1e96b.PNG)

But I am not getting these notifications banners from CometChat. I am not sure what I am missing. What and where should I put to get these banners receiving.

**Comment by pushpsenairekar2911** [comment]
Hello LiborZa, 

You have successfully configured the push notifications from firebase console. It seems that you haven't added any extensions for push notifications. Kindly, follow these steps to add an extension for push notification:

1. login into Cometchat app dashboard: http://app.cometchat.com
2. Go inside Extensions -->  All extensions --> Push Notification --> Add Extension. 
3. Enable the extension which you have added and then add Title for push notifications and FCM server key in action settings.
4. Save the settings and check the push notifications are working or not. 

Hope, this resolves your issue.

Do not hesitate to contact us if you have any queries/concerns. We'll be glad to assist you.

Warm Regards,

Pushpsen A.
CometChatPro Team

**Comment by LiborZa** [comment]
Hello @pushpsenairekar2911 ,

I have added extension for push notifications in CometChat dashboard. I was using there `Legacy server key` from Firebase console. I changed it to `Server key` but it seems it has same results. Which key should I use there? Is it okay that I set in Firebase only `APNs Authentication Key` and not `APNs Certificates`? Because I think it should be.

Thanks for info

**Comment by pushpsenairekar2911** [comment]
Hello @LiborZa,

We hope your day is going well.
You have to user Server key instead of Legacy server key. Make sure you're subscribing to the right topic. 
For reference, you can refer to this push notification sample app:
[Sample app - Push Notification](https://bit.ly/2VP6V0S)

Do not hesitate to contact us if you have any queries/concerns. We'll be glad to assist you.

Warm Regards,

Pushpsen A.
CometChatPro Team

**Comment by LiborZa** [comment]
Hello @pushpsenairekar2911 ,

I am using Server key and I subscribed to right topic. I checked several times your sample app and I have set everything right. I still dont know why it's not working.

Regards,
Libor

**Comment by bhooshanpatil** [comment]
Hey @LiborZa,
it is okay that if you set in `APNs Authentication Key ` instead of `APNs Certificates`?
we are looking into it,  we will get back to you as soon as the issue got resolved. will keep posting here.

**Comment by pushpsenairekar2911** [comment]
Hello @LiborZa,

We hope your day is going well. 

Can you provide us the App ID which you're using for the same app?  Since we are unable to replicate this issue at our end, we would like some more information so that we can try to get this issue fixed at the earliest.

Thanks.

**Comment by bhooshanpatil** [comment]
Hello @LiborZa,
received your details, please provide your `GoogleService-Info.plist` file (email: @pushpsenairekar2911 ) to thoroughly check the issue that you are currently facing in the push notification while using firebase so that we can use your app id in our sample app using demo user and try to replicate the issue at our end.

**Comment by anantgarg** [comment]
@LiborZa can you please close this issue if it's been resolved.
