### ISSUE TITLE
[1.8.8] Cannot find protocol declaration for CometChatPro Delegates. 

### ISSUE THREAD

**Issue by pushpsenairekar2911** [cometchat-pro/ios-chat-sdk#30]
**Describe the bug**
Due to Objective C and Swift Compatibility inside the project I'm not able to add CometChatUserDelegate inside the project. 

**To Reproduce**
1. add 'CometchatUserDelegate' inside the class. 
2. Click on assign the delegate in viewDidLoad

**Expected behavior**
Should not throw an error. 

**Actual behavior**
throwing an error. 

**Enviorment/Platfrom (please complete the following information):**
 - iOS Version[ e.g iOS 12.1 ]
 - CometChat SDK Version[ e.g. 1.8.8]

**Comment by jeetkapadia** [comment]
We have checked the issue and it is working fine.
