### ISSUE TITLE
[2.0.0-beta1] Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1

### ISSUE THREAD

**Issue by bobongski** [cometchat-pro/ios-chat-sdk#32]
Pod install CometChatPro 
Xcode 11 bug..
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1

**Comment by pushpsenairekar2911** [comment]
Hi @bobongski, We have added the support for Xcode 11 but currently it is not available on cocoapods. Please download CometChat Pro SDK by [Clicking here](https://bit.ly/2Mm7bUD). If you are using pods then you need to navigate to your pod project and replace the CometChat folder present inside with the folder got from the below attachment. Let us know if you face any other issue.

**Comment by bobongski** [comment]
Could not find module 'CometChatPro' for target 'x86_64-apple-ios-simulator'; found: arm64, armv7-apple-ios, arm64-apple-ios, arm, armv7 please help.

**Comment by akhiljohny** [comment]
Cannot open this link you provided
https://temp.cometchat.com/CometChatPro%20Xcode%2011%20Development%20Package.zip

**Comment by jeetkapadia** [comment]
This issue has been fixed. You can use our latest version 2.0.4 which is available for Xcode 11 and 11.2.1 versions. In case if you are using Xcode 11 then you need to specify version number-Xcode11. For example, in this case, it would be 2.0.4-Xcode11. Incase if you are using 11.2.1 Xcode version then you need to add the version number 2.0.4.

**Comment by mahmooddagga** [comment]
Failed to load module ‘CometChatPro’ After update xcode to new Version 11.4 (11E146)

@jeetkapadia

**Comment by ordizrobert** [comment]
@jeetkapadia my project is running using Xcode 11.2 but when i update it to 11.4 this happens
<img width="159" alt="Screen Shot 2020-05-15 at 5 35 33 PM" src="https://user-images.githubusercontent.com/35757206/82035841-adb76f80-96d2-11ea-88da-7456f3b4b91a.png">

<img width="406" alt="Screen Shot 2020-05-15 at 5 34 51 PM" src="https://user-images.githubusercontent.com/35757206/82035812-a55f3480-96d2-11ea-94a7-fdbaf3b96be3.png">
