### ISSUE TITLE
[2.0.0-beta] Calling not working when one device is connected to the Wifi and other is connected to the Mobile data.

### ISSUE THREAD

**Issue by pushpsenairekar2911** [cometchat-pro/ios-chat-sdk#33]
**Describe the bug**
[2.0.0-beta] Calling not working when one device is connected to the Wifi and other is connected to the Mobile data.

**To Reproduce**
1. Call the user
2. Keep one device on wifi and another on mobile data

**Expected behavior**
Calling should work.

**Actual behavior**
Calling not working.

**Comment by nmasnadithya** [comment]
To add to this, it worked without any issue when I tried this scenario in a different wifi network. But whatsapp twilio and other call apps work without a y issue I have this specific network configuration

**Comment by NishantTiwarins** [comment]
We have made modifications on our end please check with our latest version 2.0.5 and let us know if you face any other issue.
