### ISSUE TITLE
"ERROR_JSON_EXCEPTION" While setting group metadata to a non string value. 

### ISSUE THREAD

**Issue by vivekmzkl** [cometchat-pro/ios-chat-sdk#35]
When requesting groupRequest.fetchNext api, getting CometChatPro.CometChatException error of code "ERROR_JSON_EXCEPTION" while trying to set a value like integer for a string key (Example: {"id":12}) in metadata of group

**Comment by NishantTiwarins** [comment]
Hi 
Sorry for late reply. we are not able to replicate the issue. Can you please provide more specification as in CometChatSDK version, Xcode version and the code snippet where you have implemented this. This would help us find the cause of the issue and help you with your implementation.

**Comment by jeetkapadia** [comment]
Fixed issue in version 2.0.4
