### ISSUE TITLE
Version 2 beta 3 :  getting error FCM notification when end voice/video calls

### ISSUE THREAD

**Issue by raelsayied** [cometchat-pro/ios-chat-sdk#36]
**Describe the bug**
<img width="260" alt="111" src="https://user-images.githubusercontent.com/16875781/66988452-359cb300-f0cb-11e9-96f5-765adddea286.png">

i am getting a Notification with message "false" when i end any voice /  video calls

**Comment by NishantTiwarins** [comment]
We have fixed this issue. Please check this in our latest version 2.0.5. Do let us know if you face any other issue.
