### ISSUE TITLE
[2.0.1] Cannot install CometChatPro using pod

### ISSUE THREAD

**Issue by akhiljohny** [cometchat-pro/ios-chat-sdk#38]
just install CometChatPro using Pod 2.0.1 
Then terminal shows error CometChatPro is using http and only https network supported.
How to remove these error.?  I need to work my project on Xcode 11.2.1

**Comment by akhiljohny** [comment]
![Screenshot 2019-11-26 at 2 16 11 PM](https://user-images.githubusercontent.com/19851937/69613304-5d325400-1057-11ea-9a2c-c6604e1632bc.png)

**Comment by akhiljohny** [comment]
I tried in some other macs too, same error. Need help fast.

**Comment by NishantTiwarins** [comment]
Hi 
We tried this on our end also and it is installing properly. The pod will come from http only. Please try pod set up or pod repo update. 
![Screenshot 2019-11-26 at 2 15 26 PM](https://user-images.githubusercontent.com/56542484/69613597-d03bca80-1057-11ea-8110-c8ee39c6dd5c.png)

**Comment by akhiljohny** [comment]
I tried again same issue

**Comment by NishantTiwarins** [comment]
Hi 
We tried this thing on our end. Can you please share the steps that you are performing for pod install. Exact steps from start will be very helpful
Thanks

**Comment by jeetkapadia** [comment]
Hi @akhiljohny, 
Are you able to download the CometChat framework through pods? As I can see you getting a warning related to Http and its not an error. You should be able to download the framework through pods with Http as well. Can you please check your firewall that it may be blocking Http request.

**Comment by jeetkapadia** [comment]
Hi, we have released new version 2.0.4. Please try downloading and let us know if you face any issues.

**Comment by suleymancalik** [comment]
Same problem occurs while installing 2.0.9 via
pod 'CometChatPro', '2.0.9-Xcode11.4'

**Comment by NishantTiwarins** [comment]
Hi

@suleymancalik 

Can you please try now we have fixed it. Please check and let us know if you still face the issue.
