### ISSUE TITLE
Initialization CometChat CPU problem

### ISSUE THREAD

**Issue by LiborZa** [cometchat-pro/ios-chat-sdk#4]
Hi,

I was calling method below and it was working. I don't think I have problem with that but this week I found out that after calling that method (in AppDelegate in `didFinishLaunchingWithOptions` method) I get 100% usage of CPU and for next several minutes until system kills my app. It's done by this method because when I remove line with calling this method it's okay. What is weird is that when I tried app with removed calling of method below CometChat methods were still working.  On the contrary when I call this method and trying to get contacts (`UsersRequest.UsersRequestBuilder(limit: 20).build()` and fetch) I don't get any results (not success nor error callbacks are called).

```
func initializationCometChat() {
        CometChat(appId: Constants.cometChat.appId, onSuccess: { (isSuccess) in
            
            if (isSuccess) {
                print("CometChat initialization Success")
            }
        }) { (error) in
            print("CometChat initialization Error \(error.errorDescription)")
        }
    }
```

Thanks for help with fixing this issue.

**Comment by bhooshanpatil** [comment]
Hello @LiborZa,
would you please refer [This](https://github.com/cometchat-pro-samples/ios-swift-chat-app/archive/master.zip) sample app for init, login and fetch contacts.
