### ISSUE TITLE
Missing MetaData value in user object

### ISSUE THREAD

**Issue by NishantTiwarins** [cometchat-pro/ios-chat-sdk#40]
**Describe the bug**
The metaData value is missing when we call user.metaData

**To Reproduce**
1. Go to 'dashboard'
2. Click on 'User'
3. Scroll down to 'Add MetaData in the user profile tab'
4.Save it

**Expected behavior**

**Actual behavior**
The MetaData added in user from dasboard should appear in the logs whenfetching user.metaData.

**Comment by jeetkapadia** [comment]
Fixed issue in version 2.0.4
