### ISSUE TITLE
[2.0.5] Semantic Issue integration of cometChat in swift project

### ISSUE THREAD

**Issue by NishantTiwarins** [cometchat-pro/ios-chat-sdk#42]
**Describe the bug**
Integration issue of CometChat Pro SDK with objective c files.
Error :- Unable to access the methods in objective C file

**To Reproduce**
1. Do pod install of CometChat SDK in objective c app 
2. import CometChat SDK in file 
3. unable to access the methods

**Comment by jeetkapadia** [comment]
This has been fixed in the new Objective app released with SDK 2.0.5
