### ISSUE TITLE
Xcode 11.3 support

### ISSUE THREAD

**Issue by mkhoshpour** [cometchat-pro/ios-chat-sdk#45]
do you support Xcode 11.3?
when I want to upload my app to app store I get this error: 
Prepared archive for uploading
Upload failed
	error: App Store Connect Operation Error
ERROR ITMS-90206: "Invalid Bundle. The bundle at 'Apartment.app/Frameworks/CometChatPro.framework' contains disallowed file 'Frameworks'."

**Comment by jeetkapadia** [comment]
Hi,

Please remove the frameworks/ folder present inside the CometChatPro.framework. This should resolve the issue faced by you. Also please go through our release script on the following link:

https://prodocs.cometchat.com/docs/ios-resources-publishing-app-on-app-store
