### ISSUE TITLE
how to know message read by all group members

### ISSUE THREAD

**Issue by kaushiktd** [cometchat-pro/ios-chat-sdk#46]
hello, i'm developing group message i execute your demo which does not display read receipt for group message so can you please guide me how to integrate that portion

**Comment by NishantTiwarins** [comment]
Hi @kaushiktd ,

The implementation will be like the same that has been implemented for one-on-one chat. When you receive the message list for group and in that message list if the readAt and delieveredAt value is not 0 then the message has been read and delivered to all the members present in the group.

Also to see which members have read the message you can use getmessagereceipts() function. This will return the users who have marked delivery for the message or marked read.

Let me know if you have any other queries.
