### ISSUE TITLE
CometChat-Pro [2.0.6] Pro-Ext-PM [1.0.0] Module compiled with Swift 5.0 cannot be imported by the Swift 5.1.2 compiler

### ISSUE THREAD

**Issue by priyal-jain25** [cometchat-pro/ios-chat-sdk#48]
**Module compiled with Swift 5.0 cannot be imported by the Swift 5.1.2 compiler: /**
I am using Xcode 11.2.1. 

I am trying to integrate push notifications using extension from this [reference](https://prodocs.cometchat.com/v1.8/docs/ios-push-notifications#section-push-notification-extension)

I installed recommended pod   _'Pro-Ext-PN', '~> 1.0.0'_

When I try and use getMessageFrom method of PNExtension, I get error stating `Use of unresolved identifier 'PNExtension'`. 
If I try and import PNExtension I get error `Module compiled with Swift 5.0 cannot be imported by the Swift 5.1.3 compiler`

Method followed in sample app is way too different and I am not able to relate it with extensions. 

Please help!

**Comment by pushpsenairekar2911** [comment]
Hello @priyal-jain25, 

We have removed support for `Pro-Ext-PN` in v2.0, let us know which iOS SDK are you using. Also, we suggest you use our lastest SDK i.e. v2.0.6. You can use `CometChat.processMessage()` method to process the push notification.


You can download and install the latest SDK from Cocoapods using this [instructions](https://prodocs.cometchat.com/docs/ios-quick-start#section-add-the-cometchat-dependency).

**Comment by priyal-jain25** [comment]
Hi @pushpsenairekar2911,
I am using version 2.0.6. The [document](https://prodocs.cometchat.com/v1.8/docs/ios-push-notifications#section-push-notification-extension) mentions that we can directly use extensions. (Do we have to explicitly subscribe for user/group notifications)?

**Comment by anantgarg** [comment]
@priyal-jain25 the document link you've mentioned is for v1.8. Please check this document:

https://prodocs.cometchat.com/docs/ios-extensions-push-notification

Once this issue is resolved for you, please close this issue. Thank you!

**Comment by priyal-jain25** [comment]
Thanks Anant. It solved the problem.
