### ISSUE TITLE
[SDK-Version] Issue Title 

### ISSUE THREAD

**Issue by NishantTiwarins** [cometchat-pro/ios-chat-sdk#50]
Fatal Error when getting Conversation object from ActionMessage object

This issue is similar to Fatal Error when getting Conversation object from Group Call object.

Example:

func onMemberAddedToGroup(action: ActionMessage, addedBy: User, addedUser: User, addedTo: Group) {
    let _ = CometChat.getConversationFromMessage(action)
}

**Comment by jeetkapadia** [comment]
Fixed issue in 2.0.8-beta1
