### ISSUE TITLE
[2.0.7] Failed to load module ‘CometChatPro’ After update xcode to new Version 11.4 (11E146)

### ISSUE THREAD

**Issue by mahmooddagga** [cometchat-pro/ios-chat-sdk#52]
Failed to load module ‘CometChatPro’ After update xcode to new Version 11.4 (11E146)

Failed to load module 'CometChatPro'
Failed to load module 'JitsiMeet'

// swift-interface-format-version: 1.0
// swift-compiler-version: Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
// swift-module-flags: -target x86_64-apple-ios10.0-simulator -enable-objc-interop -enable-library-evolution -swift-version 5 -enforce-exclusivity=checked -Onone -module-name CometChatPro

**Comment by mahmooddagga** [comment]
@jeetkapadia @pushpsenairekar2911  @bhooshanpatil  @ghanshyammansata

**Comment by anantgarg** [comment]
@mahmooddagga we will be releasing an update in the next few days.

**Comment by NishantTiwarins** [comment]
Hi @mahmooddagga 

We have released a version for Xcode 11.4. You can do a pod install by updating the podfile to

 **pod 'CometChatPro', '2.0.8'**
