### ISSUE TITLE
Receiving call in background - show accept/reject screen

### ISSUE THREAD

**Issue by smedic** [cometchat-pro/ios-chat-sdk#53]
I am trying to implement ability to show incoming screen when somebody is calling, but it seems impossible. 
On Android, I see a screen  where I can choose to accept/reject but on iOS I see only notification.

Any idea how to implement that on iOS ?

I checked test apps present on AppStore/Play and sometimes, when app is killed in iOS, clicking on a notification opens app, but does not open calling dialog..

**Comment by pushpsenairekar2911** [comment]
Hello @smedic, 

To receive the calls in background, it requires voip based push notifications. We currently use firebase for push notifications and firebase doesn't support voip based push notifications as of now. 

We will notify you if we add push-kit support in the future.

**Comment by pushpsenairekar2911** [comment]
Hello @smedic, 

We are tracking your request for receiving call in background. You can view the full post at:
https://cometchat.canny.io/cometchat-pro-feature-requests/p/receiving-call-in-background-pushkit
