### ISSUE TITLE
Found a lot of warning due to firebase libraries.

### ISSUE THREAD

**Issue by voyager163** [cometchat-pro/ios-chat-sdk#54]
Hi CometChat,

When i run my project with cometchat libraries. i notice that there is the below warning. Will it cause any issue?

bjc[7478]: Class PodsDummy_GTMSessionFetcher is implemented in both /Users/jonathan/Library/Developer/CoreSimulator/Devices/7BE77D1D-B7EC-48E2-A9BB-DE54A35D0F7A/data/Containers/Bundle/Application/BDBB9DE8-09D4-49FA-8AC3-FC3381E7FFBF/XXX.app/Frameworks/JitsiMeet.framework/JitsiMeet (0x10739ef88) and /Users/jonathan/Library/Developer/CoreSimulator/Devices/7BE77D1D-B7EC-48E2-A9BB-DE54A35D0F7A/data/Containers/Bundle/Application/BDBB9DE8-09D4-49FA-8AC3-FC3381E7FFBF/XXX.app/Frameworks/GTMSessionFetcher.framework/GTMSessionFetcher (0x106992e20). One of the two will be used. Which one is undefined.
objc[7478]: Class GTMSessionFetcher is implemented in both /Users/jonathan/Library/Developer/CoreSimulator/Devices/7BE77D1D-B7EC-48E2-A9BB-DE54A35D0F7A/data/Containers/Bundle/Application/BDBB9DE8-09D4-49FA-8AC3-FC3381E7FFBF/XXX.app/Frameworks/JitsiMeet.framework/JitsiMeet (0x10739efb0) and /Users/jonathan/Library/Developer/CoreSimulator/Devices/7BE77D1D-B7EC-48E2-A9BB-DE54A35D0F7A/data/Containers/Bundle/Application/BDBB9DE8-09D4-49FA-8AC3-FC3381E7FFBF/XXX.app/Frameworks/GTMSessionFetcher.framework/GTMSessionFetcher (0x106992e48). One of the two will be used. Which one is undefined.
objc[7478]: Class GTMSessionCookieStorage is implemented in both /Users/jonathan/Library/Developer/CoreSimulator/Devices/7BE77D1D-B7EC-48E2-A9BB-DE54A35D0F7A/data/Containers/Bundle/Application/BDBB9DE8-09D4-49FA-8AC3-FC3381E7FFBF/XXX.app/Frameworks/JitsiMeet.framework/JitsiMeet (0x10739efd8) and /Users/jonathan/Library/Developer/CoreSimulator/Devices/7BE77D1D-B7EC-48E2-A9BB-DE54A35D0F7A/data/Containers/Bundle/Application/BDBB9DE8-09D4-49FA-8AC3-FC3381E7FFBF/XXX.app/Frameworks/GTMSessionFetcher.framework/GTMSessionFetcher (0x106992e98). One of the two will be used. Which one is undefined.
objc[7478]: Class GTMSessionFetcherService is implemented in both /Users/jonathan/Library/Developer/CoreSimulator/Devices/7BE77D1D-B7EC-48E2-A9BB-DE54A35D0F7A/data/Containers/Bundle/Application/BDBB9DE8-09D4-49FA-8AC3-FC3381E7FFBF/SwiftMED.app/Frameworks/JitsiMeet.framework/JitsiMeet (0x10739f050) and /Users/jonathan/Library/Developer/CoreSimulator/Devices/7BE77D1D-B7EC-48E2-A9BB-DE54A35D0F7A/data/Containers/Bundle/Application/BDBB9DE8-09D4-49FA-8AC3-FC3381E7FFBF/SwiftMED.app/Frameworks/GTMSessionFetcher.framework/GTMSessionFetcher (0x106992f38). One of the two will be used. Which one is undefined.
objc[7478]: Class GTMSessionFetcherSessionDelegateDispatcher is implemented in both /Users/jonathan/Library/Developer/CoreSimulator/Devices/7BE77D1D-B7EC-48E2-A9BB-DE54A35D0F7A/data/Containers/Bundle/Application/BDBB9DE8-09D4-49FA-8AC3-FC3381E7FFBF/SwiftMED.app/Frameworks/JitsiMeet.framework/JitsiMeet (0x10739f078) and /Users/jonathan/Library/Developer/CoreSimulator/Devices/7BE77D1D-B7EC-48E2-A9BB-DE54A35D0F7A/data/Containers/Bundle/Application/BDBB9DE8-09D4-49FA-8AC3-FC3381E7FFBF/SwiftMED.app/Frameworks/GTMSessionFetcher.framework/GTMSessionFetcher (0x106992f60). One of the two will be used. Which one is undefined.
objc[7478]: Class GTMSessionUploadFetcher is implemented in both /Users/jonathan/Library/Developer/CoreSimulator/Devices/7BE77D1D-B7EC-48E2-A9BB-DE54A35D0F7A/data/Containers/Bundle/Application/BDBB9DE8-09D4-49FA-8AC3-FC3381E7FFBF/SwiftMED.app/Frameworks/JitsiMeet.framework/JitsiMeet (0x10739f0f0) and /Users/jonathan/Library/Developer/CoreSimulator/Devices/7BE77D1D-B7EC-48E2-A9BB-DE54A35D0F7A/data/Containers/Bundle/Application/BDBB9DE8-09D4-49FA-8AC3-FC3381E7FFBF/XXX.app/Frameworks/GTMSessionFetcher.framework/GTMSessionFetcher (0x106992fd8). One of the two will be used. Which one is undefined.
objc[7478]: Class DDContextWhitelistFilterLogFormatter is implemented in both /Users/jonathan/Library/Developer/CoreSimulator/Devices/7BE77D1D-B7EC-48E2-A9BB-DE54A35D0F7A/data/Containers/Bundle/Application/BDBB9DE8-09D4-49FA-8AC3-FC3381E7FFBF/XXX.app/Frameworks/JitsiMeet.framework/JitsiMeet (0x10739e560) and /Users/jonathan/Library/Developer/CoreSimulator/Devices/7BE77D1D-B7EC-48E2-A9BB-DE54A35D0F7A/data/Containers/Bundle/Application/BDBB9DE8-09D4-49FA-8AC3-FC3381E7FFBF/XXX.app/Frameworks/CometChatPro.framework/CometChatPro (0x10644ee68). One of the two will be used. Which one is undefined.

**Comment by jeetkapadia** [comment]
Hi @voyager163,

The warning provided by you won’t affect the app performance in any way. We are working around the clock for better performance. However, I cannot commit anything as of now for the warnings but I can assure that it won’t have any effect on your app. Thanks

**Comment by voyager163** [comment]
I also noticed that the is connection to AWS EC2 after the chat and video is initiated. Is it due to the cometchatpro libraries
