### ISSUE TITLE
TMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSCalendarsUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data" #17

### ISSUE THREAD

**Issue by voyager163** [cometchat-pro/ios-chat-sdk#55]
Having the above issue.

It is supposed to be solved previously.

**Comment by jeetkapadia** [comment]
I have tried validating the App for Apple review process with CometChat Pro SDK and It was successfully validated without NSCalenderUsageDescription key. I have tried with the iOS Swift Sample App. Here is the link:

https://github.com/cometchat-pro-samples/ios-swift-chat-app

Thanks

**Comment by LaurentiuUngur** [comment]
@jeetkapadia this issue it's still in place. I'm using 3.0.0 beta 2. Could you please fix it ? Thanks !

**Comment by LaurentiuUngur** [comment]
@jeetkapadia any updates ? Thanks
