### ISSUE TITLE
xcode 11.4 bug

### ISSUE THREAD

**Issue by ordizrobert** [cometchat-pro/ios-chat-sdk#56]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what you exactly is happening.

**Screenshots** (optional)

**Enviorment/Platfrom (please complete the following information):**
 - iOS Version[ e.g iOS 12.1 ]
 - CometChat SDK Version[ e.g. 1.8.4]

**Files (Optional)**
 - `podfile` 

**Logs (Error Logs)**
- Error Log
- Debug Log

**Additional context**

hi, my project is already running using xcode 11.2 but when i upgraded my xcode to 11.4 this happens.

**Comment by ordizrobert** [comment]
<img width="406" alt="Screen Shot 2020-05-15 at 5 34 51 PM" src="https://user-images.githubusercontent.com/35757206/82036135-17377e00-96d3-11ea-993d-36995d38f252.png">
<img width="159" alt="Screen Shot 2020-05-15 at 5 35 33 PM" src="https://user-images.githubusercontent.com/35757206/82036158-1dc5f580-96d3-11ea-8fb1-3784cb7730de.png">

**Comment by jeetkapadia** [comment]
Hi @ordizrobert ,

We have added support for Xcode 11.4 in 1.8.12 version. Please update your CometChat Pro SDK with the 1.8.12-Xcode11.4 version in your podfile.

Thanks
