### ISSUE TITLE
[SDK-Version] Semantic issue when running on simulator for mixed project

### ISSUE THREAD

**Issue by NishantTiwarins** [cometchat-pro/ios-chat-sdk#58]
**Describe the bug**
Semantic issue when running a mixed project. This issue is occurring only when we run the project on the simulator and not on devices

**To Reproduce**
1. Open objective C sample app project 
2. Do a pod install
3. Run the app on the simulator

**Expected behavior**
It should have run on the simulator as it runs on the device

**Actual behavior**
It gives a semantic issue and does not run on the simulator.

**Comment by jeetkapadia** [comment]
Hi,

This issue is fixed in version 2.0.13.
