### ISSUE TITLE
Support Xcode 12

### ISSUE THREAD

**Issue by TitouanVanBelle** [cometchat-pro/ios-chat-sdk#59]
Xcode 12 being just in beta released, this question might be a bit premature but could you give us whenever possible an estimated release date for a CometChat iOS SDK which is compatible with this version of Xcode. We would love to be able to integrate the CometChat SDK in a swift package allowing us for more modularisation.

Thanks!

**Comment by jeetkapadia** [comment]
Hi,

We have added support for Xcode 12 in our latest release 2.0.13. You need to add the following in your pod file:
`pod 'CometChatPro', '2.0.13-Xcode12'`

Let us know if you face any other issue.

Regards
Jeet Kapadia
