### ISSUE TITLE
Support Mac Catalyst

### ISSUE THREAD

**Issue by DanBurkhardt** [cometchat-pro/ios-chat-sdk#60]
Hello, 

Supporting x86 applications running on macCatalyst is long overdue. With CometChat, I cannot distribute a universal application binary in iOS 13, which means I have to cancel my paid subscription, drop CometChat Pro for three different projects and use another company's framework. 

I don't want to do that. Please support macCatalyst for 10.15^. 

Current version tried: 'CometChatPro', '2.0.12-Xcode11.4'

**Comment by jeetkapadia** [comment]
Hi @DanBurkhardt ,

We have forwarded your request to our development team however we cannot provide any timeline for this. You can track the status on the below link:

https://feedback.cometchat.com/cometchat-pro-feature-requests/p/add-support-for-mac-cataylst

Appreciate your patience.

Thanks

**Comment by DanBurkhardt** [comment]
Is this enabled now or not?
