### ISSUE TITLE
[2.0.12-Xcode11.4] Unable to compile for simulator / x86 processors

### ISSUE THREAD

**Issue by DanBurkhardt** [cometchat-pro/ios-chat-sdk#61]
**Describe the bug**
When using this version of the SDK, Xcode is unable to compile for iOS Simulator & x86 processors

**To Reproduce**
1. Incorporate the SDK
2. Attempt to run a build to the simulator
3. See a failure

**Expected behavior**
I expect to be able to develop using a simulator when CometChat Pro is incorporated

**Actual behavior**
I am unable to use the simulator for any application that incorporates this SDK version

**Screenshots** (optional)
<img width="507" alt="Screen Shot 2020-07-16 at 3 16 36 PM" src="https://user-images.githubusercontent.com/14014682/87713198-d3670080-c777-11ea-86cf-86d4aa97455a.png">

**Enviorment/Platfrom (please complete the following information):**
 - iOS Version 13.5
 - Xcode 11.5
 - CometChat SDK Version [2.0.12-Xcode11.4]

**Files (Optional)**
 -  pod 'CometChatPro', '2.0.12-Xcode11.4'

**Logs (Error Logs)**
- see attached screenshot

**Additional context**
That's it.

**Comment by jeetkapadia** [comment]
Hi,

This issue has been fixed and will be available in the next release. We will update this thread once it is released.

Thanks

**Comment by jeetkapadia** [comment]
Hi @DanBurkhardt ,

We have added support for Xcode 11.6 (which the latest Xcode version at present) and also added support for Xcode 12 in our latest release 2.0.13. Please update to the same and let us know if you face any other issue.

Regards
Jeet Kapadia

**Comment by DanBurkhardt** [comment]
Thanks for the update! Greatly appreciated.
