### ISSUE TITLE
Module compiled with Swift 5.1.2 cannot be imported by the Swift 5.3.2 compiler

### ISSUE THREAD

**Issue by nikunjinexture** [cometchat-pro/ios-chat-sdk#63]
Unable to compile project in Xcode 12

SDK version: 1.8.7

**Comment by pushpsenairekar2911** [comment]
Hello @nikunjinexture, 

Please use the SDK v2.2.0 which is the latest one and compatible with all Xcode versions above 11. 
Also, it seems that you're using v1 SDK i.e 1.8.7. So, you need to migrate your app to v2. 

Please refer below documentation for migration: 
https://prodocs.cometchat.com/docs/ios-resources-upgrading-from-v1

v2 Sample app:
https://github.com/cometchat-pro-samples/ios-swift-chat-app

**Comment by nikunjinexture** [comment]
Thanks! It worked out for me 👍
