### ISSUE TITLE
[3.0.0-beta1] Appstore deployment issue 

### ISSUE THREAD

**Issue by sherifhasan** [cometchat-pro/ios-chat-sdk#65]
**Describe the bug**
When trying to uploading the app to app store connect using transporter I received these errors in the attached screenshot

**Notes**
I'm using pods to install the sdk 

**Screenshots** (optional)
<img width="1440" alt="Screen Shot 2021-05-04 at 8 45 14 PM" src="https://user-images.githubusercontent.com/16430626/117053765-a5a87380-ad19-11eb-9001-7cc8e39133eb.png">

**Enviorment/Platfrom **
 - iOS Version[ iOS 12.2 ]
 - CometChat SDK Version[ 3.0.0-beta1]

**Comment by abhisheksaralaya13** [comment]
Hello @sherifhasan,
App Store does not let apps be uploaded with the beta version. Currently, we are testing the beta version of the SDK, so we will be able to release the Stable version of the SDK in 2 to 3 weeks. If you want, we can give you our framework which you can replace manually.

**Comment by nethergrim** [comment]
Classic cometchat :)

**Comment by nethergrim** [comment]
same errors each time new major version appears
