### ISSUE TITLE
[2.4.2] Conflict with logger library

### ISSUE THREAD

**Issue by rahulvyas** [cometchat-pro/ios-chat-sdk#93]
**Describe the bug**
I already have sentry SDK and cocoalumberjack SDK in my pods and when I add comet chat SDK I'm getting duplicate modules.
How to fix this issue?

**Expected behavior**
It should compile

**Actual behavior**
Getting error when compiling project

**Enviorment/Platfrom :**
 - iOS Version[ iOS 11.0 ]
 - CometChat SDK Version[2.4.2]

**Logs (Error Logs)**
'DDLogMessage' has different definitions in different modules; first difference is definition in module 'CometChatPro.DDLog' found field 'logLevel'

**Comment by abhisheksaralaya13** [comment]
Hi @rahulvyas ,
Can you share your podfile and podfile.lock with us

**Comment by rahulvyas** [comment]
Here is the podfile and podfile.lock gdrive link. You can view both files

https://drive.google.com/drive/folders/1x0BiJSqHMuXvrwFZK_BRW85GSpwEYGRE?usp=sharing

**Comment by abhisheksaralaya13** [comment]
The file which you have sent is not accessible. Requesting to give access for the same

**Comment by rahulvyas** [comment]
> Hi @rahulvyas, The file which you have sent is not accessible. Requesting to give access for the same.
> 
> Regards, Abhishek Saralaya

Permission granted. let me know if you can access it.

**Comment by rahulvyas** [comment]
@abhisheksaralaya13 check this thread. 

https://stackoverflow.com/questions/55063660/how-to-exclude-a-library-out-of-framework-when-distributing-it

I think comet chat pro SDK has cocoalumberjack files inside the framework and may be due to that I'm getting this conflict. Please check the above thread and see if you can help me in fixing the issue.

**Comment by rahulvyas** [comment]
@abhisheksaralaya13 please connect with me over skype so that we can make it up and running as we have very less time to migrate. My skype id is - imrahulvyas@gmail.com

**Comment by proveshapyne** [comment]
Hey @rahulvyas,

I have reached out to you over email to take this conversation further. We can continue our communication there, and I am closing this ticket.
Thanks!

Regards,
Provesha

**Comment by abhisheksaralaya13** [comment]
CometChat v2 application uses CocoaLumberjack in dependency, so if anyone installs CocoaLumberjack in pods it will give this error. The logger issue has been resolved in v3 SDK, so this will not occur anymore in v3 application.

Thanks and Regards,
Abhishek Saralaya
