### ISSUE TITLE
[3.0.914] failed to compile in xcode 15

### ISSUE THREAD

**Issue by rahulvyas** [cometchat-pro/ios-chat-sdk#96]
**Describe the bug**
My project is not compiling in xCode 15

**Expected behavior**
It should compile properly

**Actual behavior**
These errors are coming
 'ImageResource' is ambiguous for type lookup in this context
 **Screenshots** (optional)
<img width="942" alt="Screenshot 2023-06-13 at 11 43 45 AM" src="https://github.com/cometchat-pro/ios-chat-sdk/assets/87060/82209a7e-8afd-447a-9607-b2260fbad860">

**Enviorment/Platfrom :**
 - iOS Version[ e.g iOS 17]
 - CometChat SDK Version[ 3.0.914]

**Comment by rahulvyas** [comment]
When I can expect a fix for this? The SDK should compile in both xcode 14 and xcode 15

**Comment by rahulvyas** [comment]
How long it will take?

**Comment by rahulvyas** [comment]
It's already around a week. If you want I can share more details.

The issue is coming in CometChatKingFisher library source code. The team has to update the code and resolve the conflicting things. That should fix the issue I belive.

**Comment by proveshapyne** [comment]
Hi @rahulvyas,

I wanted to let you know our team has taken up this task on priority and we will notify you as soon as we have a fix made live.
In the meantime, please [create a ticket](https://help.cometchat.com/hc/en-us/requests/new) is you have any other questions or concerns.

Thank you.

Provesha Pyne
CometChat Support

**Comment by rahulvyas** [comment]
> Mathews (CometChat Team) replied:
> 
> Hi Rahul, Please share when exactly you are facing this issue with steps that may help reproduce the problem if possible. What are the exact Xcode and iOS versions you are facing this issue on? Are you running this on a physical device or simulator?
> 
> Thanks and Regards,
> 
> Mathews Mathai Software Developer CometChat

I'm using xcode 15 beta and iOS 17 simulator. The issue occurs when I try to compile the project

**Comment by rahulvyas** [comment]
How long it will take just to fix a small issue?

**Comment by rahulvyas** [comment]
How long it will take just to fix a small issue?

**Comment by rahulvyas** [comment]
Prathamesh can you tell me release candidate version. Do I need to update the comet chat SDK or are you talking about xcode?

**Comment by rahul-sysquare** [comment]
I'm still getting the same issues in xcode 15.2 which version should I use?
